### ISSUE TITLE
Is there a particular reason why Socket is being used instead of TcpClient?

### ISSUE THREAD

**Issue by cyberinferno** [Fraysa/Destiny#10]
In this line of code:

https://github.com/Fraysa/Destiny/blob/ac46f5142d19fbb7bd43a504f06adfb6fd91629d/src/WvsLogin/WvsLogin.cs#L141

**Comment by Fraysa** [comment]
TcpClient is just a wrapper for Socket, might save a few lines. Purely a style choice :).
