### ISSUE TITLE
Hang on Login after autogeneration of account.

### ISSUE THREAD

**Issue by Bia10** [Fraysa/Destiny#11]
If you have server setup with autogeneration feature once your account is saved to database the client hangs endlessly on login screen with login button pressed. At least disconnect or restart message should be sent to client.

**Comment by Fraysa** [comment]
By that do you mean that it doesn’t automatically login (show you the world screen) after auto registering a new account? It just hangs on the login screen?

**Comment by Bia10** [comment]
1.Start the server with none account in DB
2.Have Autogeneration feature on
3.Open Maplestory put information press login once ...
4.On second login press autogeneration code is ran.
5.Once the autogenerated account is saved into DB were at  line `this.Account.Save();`
6.The client by now hangs on login screen with login button pressed doing nothing.

if its not possible for it to proceed with login which may somehow correlate with the fact that auto generated accounts cannot login due to hash mismatch which happens after you restart the hanging client then at least disconnect them.

**Comment by Bia10** [comment]
Can be closed for now.
