### ISSUE TITLE
guideline for client

### ISSUE THREAD

**Issue by zzz66686** [Fraysa/Destiny#6]
This is really excellent work. But is there any guideline for how to configure maplestory client to connect to  my server?

**Comment by Fraysa** [comment]
You'll need to download a client called "localhost" for the specific v.83
version (you can Google it and find one). Make sure the IP is set to
localhost. Place it in your v.83 MapleStory folder and run it.

**Comment by zzz66686** [comment]
Thanks, but where can I find the Chinese version of localhost v.83 ?

**Comment by Fraysa** [comment]
This emulator is designed for the English client

בתאריך 30 באוק׳ 2017 4:54 לפנה״צ,‏ "zzz66686" <notifications@github.com>
כתב:

**Comment by zzz66686** [comment]
![default](https://user-images.githubusercontent.com/14144972/32283435-43e1578a-bf5f-11e7-92cd-f16a288b2cdd.png)

Thanks for replying and I'm now trying to build and run this emulator. But I think there is something wrong when executing the SQL scripts, which is shown in the above picture. This error will not appear when I run WvsLogin for the second time, but no table is created in the 'login' database. This error also exists in the WvsGame(s). How to fix it？

I'm a MapleStory lover. When I manage to run this emulator, I will try to translate it into Chinese. And I might try to keep updating synchronously with the official server by reverse analysis and network analysis. At last, I wish that I can contribute to Destiny repo at some future days.

**Comment by zzz66686** [comment]
I have fixed this error by searching stackoverflow. The page is: 
https://stackoverflow.com/questions/8645889/there-can-be-only-one-auto-column

**Comment by zzz66686** [comment]
There is another bug: the account which is autoregistered will not be encrypted with salt.  Because  this.Account.Salt is generated after the password get encrypted.

**Comment by zzz66686** [comment]
![default](https://user-images.githubusercontent.com/14144972/32332794-5459fa1e-c021-11e7-8edb-8a48a16410b4.png)
The game get stucked because no tutoChatNPC.lua, how to write the lua?

**Comment by Fraysa** [comment]
There is support for basic NPC Lua scripting, but the scripts haven't been implemented yet so therefore it will fail to load existing NPCs scripts. Take reference using the basic script I uploaded [here](https://github.com/Fraysa/Destiny/blob/master/scripts/npc/9900000.lua).
