### ISSUE TITLE
Error when logging into a manually made account.

### ISSUE THREAD

**Issue by Nyuku** [Fraysa/Destiny#9]
Well, when I log into the server via a clean v83 localhost (well, it just has this windowed mode by default) An error appears:
![image](https://user-images.githubusercontent.com/28018026/33251760-eb4ee9da-d317-11e7-9896-7f1472565044.png)

I'm not sure if it's because I have created the account wrongly or something else. 
By the way, is the autoregister working?

**Comment by Bia10** [comment]
How did you made your account manually especially the password?
No the autoregister doesn't seem to work at least for me it gets stuck on incorrect password... ill try to check it later.

**Comment by Bia10** [comment]
well its weird every autogenerated account fails on this line 

`WvsLogin.exe!Destiny.Network.LoginClient.Login(Destiny.Network.Packet iPacket = {Destiny.Network.Packet}) Line 125`

which basically claims that 

`if (SHACryptograph.Encrypt(SHAMode.SHA512, password + this.Account.Salt) != this.Account.Password)`

is true, that implies invalid password. but how is that possible if during auto-generation this line is passed 

`this.Account.Password = SHACryptograph.Encrypt(SHAMode.SHA512, password + this.Account.Salt);`

i have checked that password is same, salt generated is same, encryption mode same and it results in same password and yet the code still enters invalid password branch ... i dont get it, going to investigate further if all fails ill bypass it for now.

**Comment by Bia10** [comment]
well it turns out that indeed the hash is different for same input i dont know why..
with same password and salt:

```
string generatedPass = SHACryptograph.Encrypt(SHAMode.SHA512, password + this.Account.Salt);
generatedPass = "e4efffb79e9ba37ad1399c2050e345a90db7f96541c2e974fd57f52868ddab315e90444d295eb1176d78818913c9a1822771cf54376de338a074bb192852de61"

this.Account.Password = SHACryptograph.Encrypt(SHAMode.SHA512, password + this.Account.Salt);
this.Account.Password = "c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec"

if (generatedPass != this.Account.Password)
{
//invalid pass
}
```
well time to check further

**Comment by Fraysa** [comment]
Try to manually add an account to the database with a password generated from a website that can generate SHA512.

It should work fine.

**Comment by TehCupcakes** [comment]
Apparently this was fixed because auto-register is working perfectly for me.

Take note that the first login attempt will indicate account id does not exist. You have to repeat the same username and password in order for auto-login to kick in. **This is a feature.** It is to reduce the likelihood of excessive accounts being created because a user mistyped their username.

It would be nice if this was configurable, but not a bug. It does create and account and log you in, and the hashed password is correct when created from auto-register.
